# Generated by Django 6.1 on 2026-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Link to YouTube video or MP4 demo clip', null=True),
        ),
    ]
